on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: say hello
        run: |
          echo "Hello from Hagital!"
          echo "Live troubleshooting script"
          echo "This is a Devops class"
      
